import { PublicLayout } from '../components/layout/PublicLayout';

const TermsPage = () => {
  return (
    <PublicLayout>
      <div className="py-24 bg-[#050505]">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>
          <p className="text-[#A1A1AA] mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

          <div className="prose prose-invert max-w-none">
            <div className="space-y-8 text-[#A1A1AA]">
              <section>
                <h2 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
                <p>
                  By accessing or using ClipTag AI ("Service"), you agree to be bound by these Terms of Service. 
                  If you do not agree to these terms, please do not use our Service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">2. Description of Service</h2>
                <p>
                  ClipTag AI provides AI-powered tools for video content creation, including but not limited to 
                  clip generation, story creation, voiceover scripts, transcriptions, and SEO optimization. 
                  The Service is provided "as is" and we reserve the right to modify, suspend, or discontinue 
                  any aspect of the Service at any time.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">3. User Accounts</h2>
                <p className="mb-3">
                  To access certain features, you must create an account. You agree to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Provide accurate and complete registration information</li>
                  <li>Maintain the security of your account credentials</li>
                  <li>Accept responsibility for all activities under your account</li>
                  <li>Notify us immediately of any unauthorized use</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">4. Subscription and Payment</h2>
                <p className="mb-3">
                  ClipTag AI offers subscription-based plans. By subscribing, you agree to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Pay all applicable fees for your selected plan</li>
                  <li>Automatic renewal unless cancelled before the renewal date</li>
                  <li>Our right to change pricing with 30 days notice</li>
                </ul>
                <p className="mt-3">
                  Refunds are available within 7 days of initial purchase if you are unsatisfied with the Service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">5. User Content</h2>
                <p className="mb-3">
                  You retain ownership of content you create using our Service. However, you grant us a 
                  limited license to store and process your content solely for providing the Service. 
                  You agree not to use the Service to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Create illegal, harmful, or offensive content</li>
                  <li>Infringe on intellectual property rights of others</li>
                  <li>Distribute malware or engage in hacking activities</li>
                  <li>Violate any applicable laws or regulations</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">6. AI-Generated Content</h2>
                <p>
                  Content generated by our AI tools is provided for your use. You are responsible for 
                  reviewing and editing AI-generated content before publication. We do not guarantee 
                  the accuracy, completeness, or suitability of AI-generated content for any purpose.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">7. Intellectual Property</h2>
                <p>
                  The Service, including its design, features, and technology, is owned by ClipTag AI 
                  and protected by intellectual property laws. You may not copy, modify, or reverse 
                  engineer any part of the Service without our written permission.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">8. Limitation of Liability</h2>
                <p>
                  To the maximum extent permitted by law, ClipTag AI shall not be liable for any indirect, 
                  incidental, special, consequential, or punitive damages resulting from your use of the 
                  Service. Our total liability shall not exceed the amount you paid for the Service in 
                  the twelve months preceding the claim.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">9. Termination</h2>
                <p>
                  We may terminate or suspend your account at any time for violations of these terms. 
                  You may cancel your account at any time. Upon termination, your right to use the 
                  Service will immediately cease.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">10. Changes to Terms</h2>
                <p>
                  We may update these terms from time to time. We will notify you of significant changes 
                  via email or through the Service. Continued use after changes constitutes acceptance 
                  of the new terms.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-white mb-4">11. Contact Information</h2>
                <p>
                  For questions about these Terms of Service, please contact us at:{' '}
                  <a href="mailto:morteglobalonline@gmail.com" className="text-[#FF5F1F] hover:underline">
                    morteglobalonline@gmail.com
                  </a>
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
};

export default TermsPage;
